// GITHUB PROCESS

// copy the link in order to clone the file from github

// On the terminal, make sure we are in the right folder (usually the desktop) that we want to eventually clone the file to

// on the terminal, type "git clone {PASTE URL LINK FOR CLONE}"

// On the desktop (if that's where terminal was positioned), the folder should appear

// Open the file on desktop and make desired edits to file

// in terminal, go to the folder you just cloned

// after the edits are made to the file, type "git status" and thefile name should appear in red

// in terminal, type "git add ."

// type "git status" and the file name(s) should appear green this time

// type "git commit -m {INCLUDE MESSAGE HERE}"

// TYPE "git status" and file should appear in white

// type "git push origin master" (NOTE: IF CHANGES HAVE BEEN MADE BY SOMEONE 
// ELSE AT THIS TIME TO THE MASTER FILE ON GITHUB, I NEED TO TYPE "git pull -r origin master" IN ORDER TO 
// GET THE MOST RECENT VERSION OF THE FILE)